In [6]:
import pandas as pd
import pyarrow.parquet as pq
from SEIR.utils import config
import SEIR.NPI as NPI
import os

snpi_fn = "model_output/snpi/USA/inference/med/mytestrun/global/intermediate/000000001.000000001.000000003.mytestrun.snpi.parquet"
config.set_file("config_inference_scenarios_statelevel_baseline_med_vacc_masks.yml")
npi_config = config["interventions"]["settings"]["vaccination"]
geoids = pd.read_csv(f"""{config["spatial_setup"]["base_path"]}/{config["spatial_setup"]["geodata"].as_str()}""",dtype="str")["geoid"].tolist()
config_npi = NPI.NPIBase.execute(
  npi_config=npi_config,
  global_config=config,
  geoids = geoids
)
file_npi = NPI.NPIBase.execute(
  npi_config=npi_config,
  global_config=config,
  loaded_df = pq.read_table(snpi_fn).to_pandas(),
  geoids = geoids
)
config_res = config_npi.getReduction("transition_rate 0")
file_res = file_npi.getReduction("transition_rate 0")
## do some comparison here

CF: transition_rate 0
CF: transition_rate 0
CF: transition_rate 1
DF: transition_rate 0
DF: transition_rate 0
DF: transition_rate 1

In [12]:
pq.read_table(snpi_fn).to_pandas()

,geoid,npi_name,start_date,end_date,parameter,reduction
0,69000,local_variance,2020-01-01,2021-02-20,r0,-0.091321
1,78000,local_variance,2020-01-01,2021-02-20,r0,-0.130023
2,66000,local_variance,2020-01-01,2021-02-20,r0,-0.211296
3,56000,local_variance,2020-01-01,2021-02-20,r0,0.169420
4,50000,local_variance,2020-01-01,2021-02-20,r0,-0.211246
...,...,...,...,...,...,...
1124,42000,Dose2_jan_B,2021-01-16,2021-01-31,transition_rate 1,0.000315
1125,36000,Dose2_jan_B,2021-01-16,2021-01-31,transition_rate 1,0.000315
1126,12000,Dose2_jan_B,2021-01-16,2021-01-31,transition_rate 1,0.000315
1127,48000,Dose2_jan_B,2021-01-16,2021-01-31,transition_rate 1,0.000315
1128,06000,Dose2_jan_B,2021-01-16,2021-01-31,transition_rate 1,0.000315

In [15]:
pq.read_table('model_output/spar/USA/inference/med/mytestrun/global/intermediate/000000001.000000000.mytestrun.spar.parquet').to_pandas()

       value                     parameter
0   1.000000                         alpha
1   2.612358                            R0
2   0.192308                         sigma
3   0.263035                         gamma
4   3.000000       n_parallel_compartments
5   0.000000    0 susceptibility reduction
6   0.500000    1 susceptibility reduction
7   0.950000    2 susceptibility reduction
8   0.000000  0 transmissibility reduction
9   0.000000  1 transmissibility reduction
10  0.000000  2 transmissibility reduction
11  2.000000        n_parallel_transitions
12  0.000000             0 transition rate
13  0.000000             1 transition rate
14  0.000000             0 transition from
15  1.000000             1 transition from
16  1.000000               0 transition to
17  2.000000               1 transition to

In [2]:
seir = pq.read_table("model_output/seir/USA/inference/med/mytestrun/global/intermediate/000000001.000000001.mytestrun.seir.parquet").to_pandas()
seir

,comp,p_comp,69000,78000,66000,56000,50000,11000,02000,38000,...,37000,13000,39000,17000,42000,36000,12000,48000,06000,time
0,S,0.0,53883.0,106405.0,159385.0,581024.0,624313.0,692683.0,737068.0,756717.0,...,10264876.0,10403847.0,11655397.0,12770631.0,12791530.0,19572319.0,20901636.0,28260856.0,39283497.0,2020-01-01
1,S,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
2,S,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
3,E,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
4,E,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2020-01-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10003,cumI,1.0,101.0,0.0,0.0,4.0,95.0,0.0,0.0,2190.0,...,545.0,6962.0,0.0,0.0,0.0,314.0,1066.0,2735.0,0.0,2021-02-20
10004,cumI,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,5.0,21.0,0.0,0.0,0.0,0.0,5.0,10.0,0.0,2021-02-20
10005,diffI,0.0,45.0,0.0,0.0,3.0,35.0,0.0,0.0,743.0,...,301.0,1230.0,0.0,0.0,0.0,144.0,204.0,2614.0,0.0,2021-02-20
10006,diffI,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,...,20.0,73.0,0.0,0.0,0.0,4.0,9.0,133.0,0.0,2021-02-20
10007,diffI,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021-02-20

In [11]:
outcome = pq.read_table("model_output/hosp/USA/inference/med/mytestrun/global/intermediate/000000001.000000001.000000002.mytestrun.hosp.parquet").to_pandas()
outcome[outcome['p_comp'] == 0.0].sum()

p_comp                                                       0
geoid        6900069000690006900069000690006900069000690006...
incidI                                             9.04255e+07
incidH                                             1.54884e+06
hosp_curr                                          1.07356e+07
incidD                                                  417497
incidICU                                                255817
icu_curr                                           2.02148e+06
incidVent                                               118016
vent_curr                                               817262
incidC                                             2.24607e+07
dtype: object