In [86]:
import pandas as pd
import numpy as np
import datetime

a = []
for i in range(1000):
    sim = pd.read_csv(f'model_output/SanFrancisco/mid/sim_{i}_scn_midSF.csv')
    sim = sim[sim['comp']=='diffI']
    a.append(int(sim[sim['time']=='2020-03-09'].sum(axis=1)))

In [87]:
print('mean', np.mean(a), 'median', np.median(a), '20th',np.quantile(a, .2), '80th', np.quantile(a, .8))

mean 1522.155 median 991.0 20th 364.8 80th 2477.4

In [77]:
a = []
for i in range(1000):
    sim = pd.read_csv(f'model_output/SanFrancisco/mid/sim_{i}_scn_midSF.csv')
    sim1 = sim[sim['comp']=='I1']
    a.append(int(sim1[sim1['time']=='2020-03-09'].sum(axis=1)))
    sim2 = sim[sim['comp']=='I2']
    a[i] = a[i] + int(sim2[sim2['time']=='2020-03-09'].sum(axis=1))
    sim3 = sim[sim['comp']=='R']
    a[i] = a[i] + int(sim3[sim3['time']=='2020-03-09'].sum(axis=1))

In [78]:
print('mean', np.mean(a), 'median', np.median(a), '20th',np.quantile(a, .2), '80th', np.quantile(a, .8))

mean 790.804 median 478.5 20th 165.0 80th 1303.2

In [80]:
sim['comp'].unique()

array(['S', 'E', 'I1', 'I2', 'R', 'cumI', 'diffI', '7.0'], dtype=object)

In [82]:
sim[sim['time'] == '2020-03-09']

,time,comp,6001,6003,6005,6007,6009,6011,6013,6015,...,6097,6099,6101,6103,6105,6107,6109,6111,6113,6115
368,2020-03-09,S,1676171.0,1176.0,38185.0,229494.0,45934.0,21401.0,1145002.0,27423.0,...,495057.0,533674.0,94515.0,63077.0,13000.0,457347.0,52937.0,840701.0,210918.0,73638.0
369,2020-03-09,E,229.0,0.0,2.0,8.0,4.0,1.0,171.0,2.0,...,83.0,33.0,2.0,9.0,0.0,3.0,0.0,4.0,14.0,3.0
370,2020-03-09,I1,60.0,0.0,1.0,3.0,1.0,0.0,39.0,0.0,...,21.0,11.0,0.0,3.0,0.0,0.0,0.0,1.0,5.0,0.0
371,2020-03-09,I2,36.0,0.0,1.0,1.0,0.0,0.0,38.0,0.0,...,18.0,11.0,1.0,0.0,0.0,2.0,0.0,3.0,5.0,1.0
372,2020-03-09,R,44.0,0.0,0.0,0.0,0.0,0.0,27.0,0.0,...,11.0,5.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0
373,2020-03-09,cumI,131.0,0.0,1.0,3.0,2.0,2.0,86.0,1.0,...,29.0,30.0,3.0,1.0,1.0,2.0,0.0,4.0,15.0,0.0
374,2020-03-09,diffI,259.0,0.0,3.0,5.0,3.0,0.0,202.0,0.0,...,75.0,41.0,3.0,8.0,0.0,1.0,0.0,9.0,37.0,3.0
375,2020-03-09,7.0,32.0,0.0,1.0,3.0,1.0,0.0,24.0,0.0,...,10.0,10.0,0.0,1.0,0.0,0.0,0.0,2.0,5.0,0.0

,time,comp,6001,6003,6005,6007,6009,6011,6013,6015,...,6097,6099,6101,6103,6105,6107,6109,6111,6113,6115
0,2020-01-23,S,1644006.0,1144.0,37854.0,227113.0,45204.0,21435.0,1133540.0,27425.0,...,501318.0,539309.0,95905.0,63366.0,12856.0,460418.0,53932.0,847952.0,214817.0,75485.0
1,2020-01-23,E,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2020-01-23,I1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2020-01-23,I2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2020-01-23,R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
555,2020-04-01,I2,81.0,0.0,1.0,4.0,1.0,0.0,46.0,0.0,...,22.0,22.0,4.0,2.0,1.0,2.0,2.0,0.0,6.0,3.0
556,2020-04-01,R,48.0,0.0,0.0,3.0,5.0,2.0,30.0,0.0,...,10.0,15.0,2.0,1.0,0.0,5.0,0.0,2.0,6.0,1.0
557,2020-04-01,cumI,291.0,0.0,6.0,23.0,6.0,2.0,178.0,0.0,...,61.0,95.0,12.0,6.0,0.0,18.0,2.0,9.0,35.0,15.0
558,2020-04-01,diffI,471.0,0.0,3.0,18.0,13.0,2.0,334.0,0.0,...,176.0,141.0,23.0,10.0,0.0,26.0,6.0,11.0,51.0,21.0
559,2020-04-01,7.0,38.0,0.0,0.0,2.0,1.0,1.0,32.0,0.0,...,8.0,6.0,2.0,1.0,0.0,2.0,2.0,0.0,6.0,3.0